services:
  - type: web
    name: chillers
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install; npm run build
    startCommand: npm run start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PROWLARR_URL
        value: http://prowlarr:9696
      - key: TORRSERVER_URL
        value: http://torrserver:8090
      - key: PROWLARR_API_KEY
        sync: false
    healthCheckPath: /api/health

  - type: web
    name: prowlarr
    env: docker
    plan: free
    image:
      url: linuxserver/prowlarr:latest
    envVars:
      - key: PUID
        value: "1000"
      - key: PGID
        value: "1000"
      - key: TZ
        value: Etc/UTC

  - type: web
    name: torrserver
    env: docker
    plan: free
    image:
      url: yourok/torrserver:latest
