// @ts-nocheck
// Catalogue curé de chaînes gratuites/publiques avec priorité Sport.
exports.LIVE_SEED = [
    // ── Sports (Priorité #1) ────────────────────────────────────────────────
    {
        name: 'beIN SPORTS XTRA',
        slug: 'bein-sports-xtra',
        categories: ['sports'],
        country: 'US',
        language: 'fra',
        streamUrl: 'https://bein-xtra-bein.amagi.tv/playlist.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/BeIN_Sports_logo.svg/512px-BeIN_Sports_logo.svg.png',
        aliases: ['bein sports xtra', 'bein xtra', 'bein sport'],
        order: 1,
    },
    {
        name: 'beIN SPORTS XTRA HD',
        slug: 'bein-sports-xtra-hd',
        categories: ['sports'],
        country: 'US',
        language: 'eng',
        streamUrl: 'https://bein-xtra-samsungus.amagi.tv/playlist.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/BeIN_Sports_logo.svg/512px-BeIN_Sports_logo.svg.png',
        aliases: ['bein sports xtra hd', 'bein sports english'],
        order: 2,
    },
    {
        name: 'Red Bull TV (Sports & Action)',
        slug: 'red-bull-tv',
        categories: ['sports'],
        country: 'FR',
        language: 'fra',
        streamUrl: 'https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Red_Bull_logo.svg/512px-Red_Bull_logo.svg.png',
        aliases: ['red bull tv', 'red bull sports'],
        order: 3,
    },
    {
        name: 'Fight Sports HD',
        slug: 'fight-sports-hd',
        categories: ['sports'],
        country: 'US',
        language: 'eng',
        streamUrl: 'https://amg01644-anthem-fntv-samsungus-o2tce.amagi.tv/playlist.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Fight_Network_logo.svg/512px-Fight_Network_logo.svg.png',
        aliases: ['fight sports', 'fight network'],
        order: 4,
    },
    {
        name: 'World Poker Tour',
        slug: 'world-poker-tour',
        categories: ['sports', 'entertainment'],
        country: 'US',
        language: 'eng',
        streamUrl: 'https://amg00778-amg00778c1-wpt-samsungus-1863.playout.now3.amagi.tv/playlist/amg00778-worldpokertour-wpt-samsungus/playlist.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/91/World_Poker_Tour_logo.svg/512px-World_Poker_Tour_logo.svg.png',
        aliases: ['wpt', 'world poker tour'],
        order: 5,
    },
    // ── Chaînes réelles repérées derrière LiveBall (flux directs) ─────────────
    {
        name: 'FOX Sports (US)',
        slug: 'fox-sports-us',
        categories: ['sports'],
        country: 'US',
        language: 'eng',
        streamUrl: 'https://d1jzu95oc8fgt3.cloudfront.net/FOX_Sports.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/FOX_Sports_logo.svg/512px-FOX_Sports_logo.svg.png',
        aliases: ['fox sports us', 'fox sports 24 7', 'fox sports us fast'],
        order: 6,
    },
    {
        name: 'Fox Sports 2 (US)',
        slug: 'fox-sports-2-us',
        categories: ['sports'],
        country: 'US',
        language: 'eng',
        streamUrl: 'https://tvsen7.aynascope.net/foxsports2/index.m3u8',
        logo: 'https://i.imgur.com/LHtxKI8.png',
        aliases: ['fox sports 2', 'foxsports2', 'fox2'],
        order: 7,
    },
    {
        name: 'ESPN8 The Ocho',
        slug: 'espn8-the-ocho',
        categories: ['sports'],
        country: 'US',
        language: 'eng',
        streamUrl: 'https://d3b6q2ou5kp8ke.cloudfront.net/ESPNTheOcho.m3u8',
        logo: 'https://images.fubo.tv/channel-config-ui/station-logos/on-dark/espn_8_the_ocho_bw.png',
        aliases: ['espn8', 'espn the ocho', 'espn ocho'],
        order: 8,
    },
    {
        name: 'fubo Sports Network',
        slug: 'fubo-sports-network',
        categories: ['sports'],
        country: 'US',
        language: 'eng',
        streamUrl: 'https://dnf08l6u6uxnz.cloudfront.net/master.m3u8',
        logo: 'https://i.imgur.com/qFNRJLb.png',
        aliases: ['fubo sports network', 'fubo sports'],
        order: 9,
    },
    {
        name: 'Goal TV',
        slug: 'goal-tv',
        categories: ['sports'],
        country: 'US',
        language: 'eng',
        streamUrl: 'https://streams2.sofast.tv/sofastplayout/WiseM3U8_1/master.m3u8',
        logo: '',
        aliases: ['goal tv', 'goal channel'],
        order: 10,
    },
    {
        name: 'FloHockey 24/7',
        slug: 'flohockey-24-7',
        categories: ['sports'],
        country: 'US',
        language: 'eng',
        streamUrl: 'https://amg02278-amg02278c2-flosports-worldwide-9916.playouts.now.amagi.tv/playlist.m3u8',
        logo: 'https://images.fubo.tv/channel-config-ui/station-logos/on-dark/flohockey-white.png',
        aliases: ['flohockey 24 7', 'flo hockey'],
        order: 11,
    },
    {
        name: 'FloRacing 24/7',
        slug: 'floracing-24-7',
        categories: ['sports'],
        country: 'US',
        language: 'eng',
        streamUrl: 'https://amg02278-amg02278c1-flosports-worldwide-7592.playouts.now.amagi.tv/playlist.m3u8',
        logo: 'https://images.fubo.tv/channel-config-ui/station-logos/on-dark/floracing-white.png',
        aliases: ['floracing 24 7', 'flo racing'],
        order: 12,
    },
    {
        name: 'Stingray Soccer Anthems',
        slug: 'stingray-soccer-anthems',
        categories: ['sports'],
        country: 'CA',
        language: 'eng',
        streamUrl: 'https://lotus.stingray.com/manifest/ose-347ads-montreal/samsungtvplus/master.m3u8',
        logo: '',
        aliases: ['stingray soccer anthems', 'soccer anthems'],
        order: 13,
    },
    // ── France & Généraliste ──────────────────────────────────────────────────
    {
        name: 'France 24 Français',
        slug: 'france-24-francais',
        categories: ['news'],
        country: 'FR',
        language: 'fra',
        streamUrl: 'https://static.france24.com/live/F24_FR_LO_HLS/live_web.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/France_24_logo.svg/512px-France_24_logo.svg.png',
        aliases: ['france 24 francais', 'france 24', 'france24'],
        order: 6,
    },
    {
        name: 'TV5MONDE Europe',
        slug: 'tv5monde-europe',
        categories: ['general'],
        country: 'FR',
        language: 'fra',
        streamUrl: 'https://ott.tv5monde.com/Content/HLS/Live/channel(fbs)/variant.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/TV5MONDE_logo.svg/512px-TV5MONDE_logo.svg.png',
        aliases: ['tv5monde europe', 'tv5monde'],
        order: 7,
    },
    {
        name: 'Euronews Français',
        slug: 'euronews-francais',
        categories: ['news'],
        country: 'FR',
        language: 'fra',
        streamUrl: 'https://2f6c5bf4.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/UmxheHhUVi1ldV9FdXJvbmV3c0ZyYW5jYWlzX0hMUw/playlist.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Euronews_2016_logo.svg/512px-Euronews_2016_logo.svg.png',
        aliases: ['euronews francais', 'euronews french'],
        order: 8,
    },
    {
        name: 'LCP Assemblée nationale',
        slug: 'lcp-assemblee-nationale',
        categories: ['politics'],
        country: 'FR',
        language: 'fra',
        streamUrl: 'https://stream.lcp.fr/lcp-direct/live/playlist.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/LCP_logo.svg/500px-LCP_logo.svg.png',
        aliases: ['lcp assemblee nationale', 'lcp', 'lcp an'],
        order: 9,
    },
    {
        name: 'Public Sénat',
        slug: 'public-senat',
        categories: ['politics'],
        country: 'FR',
        language: 'fra',
        streamUrl: 'https://fms-publicsenat.yacast.fr/senat-public/live.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/5/52/Logo_Public_S%C3%A9nat_2019.svg/512px-Logo_Public_S%C3%A9nat_2019.svg.png',
        aliases: ['public senat', 'senat public'],
        order: 10,
    },
    // ── International ───────────────────────────────────────────────────────
    {
        name: 'Sky News',
        slug: 'sky-news',
        categories: ['news'],
        country: 'UK',
        language: 'eng',
        streamUrl: 'https://jmp2.uk/plu-55b285cd2665de274553d66f.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Sky_News_logo_2018.svg/512px-Sky_News_logo_2018.svg.png',
        aliases: ['sky news', 'skynews'],
        order: 11,
    },
    {
        name: 'Bloomberg Originals',
        slug: 'bloomberg-originals',
        categories: ['business', 'documentary'],
        country: 'US',
        language: 'eng',
        streamUrl: 'https://86fdc85a.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/TEctZ2JfQmxvb21iZXJnT3JpZ2luYWxzX0hMUw/playlist.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Bloomberg_Television_logo.svg/512px-Bloomberg_Television_logo.svg.png',
        aliases: ['bloomberg originals'],
        order: 12,
    },
    {
        name: 'DW English',
        slug: 'dw-english',
        categories: ['news'],
        country: 'DE',
        language: 'eng',
        streamUrl: 'https://amg01644-amg01644c1-amgplt0343.playout.now3.amagi.tv/ts-eu-w1-n2/playlist/amg01644-amg01644c1-amgplt0343/playlist.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Deutsche_Welle_logo.svg/512px-Deutsche_Welle_logo.svg.png',
        aliases: ['dw english', 'deutsche welle english'],
        order: 13,
    },
    {
        name: 'NHK World Japan',
        slug: 'nhk-world-japan',
        categories: ['news'],
        country: 'JP',
        language: 'eng',
        streamUrl: 'https://masterpl.hls.nhkworld.jp/hls/w/live/smarttv.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/NHK_World_Japan_2020.svg/512px-NHK_World_Japan_2020.svg.png',
        aliases: ['nhk world japan', 'nhk world', 'nhkworld'],
        order: 14,
    },
    {
        name: 'Al Jazeera English',
        slug: 'al-jazeera-english',
        categories: ['news'],
        country: 'QA',
        language: 'eng',
        streamUrl: 'https://live-hls-web-aje.getaj.net/AJE.m3u8',
        referer: 'https://www.aljazeera.net/',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f2/Al_Jazeera_English_logo.svg/512px-Al_Jazeera_English_logo.svg.png',
        aliases: ['al jazeera english', 'aljazeera english'],
        order: 15,
    },
];
