"""Generate the mobile splash assets.

- assets/brand/mark.webp : centred crystal-C mark used by the Flutter splash
- lib/screens/splash/splash_beams.dart : per-column silhouette profile sampled
  from that mark, so the laser beams trace the real logo outline at runtime
  without decoding pixels on the phone.
"""
from PIL import Image, ImageFilter
import os

SRC = "brand/intro/assets/chillers-logo-2k.png"
OUT_WEBP = "mobile/assets/brand/mark.webp"
OUT_DART = "mobile/lib/screens/splash/splash_beams.dart"
COLS = 56

mark = Image.open(SRC).convert("RGBA")
a = mark.split()[3]
g = mark.crop(a.getbbox())
side = int(max(g.size) * 1.02)
pad = Image.new("RGBA", (side, side), (0, 0, 0, 0))
pad.paste(g, ((side - g.width) // 2, (side - g.height) // 2))

os.makedirs(os.path.dirname(OUT_WEBP), exist_ok=True)
big = pad.resize((768, 768), Image.Resampling.LANCZOS).filter(ImageFilter.UnsharpMask(2, 90, 1))
big.save(OUT_WEBP, "WEBP", quality=92, method=6)
print(f"{OUT_WEBP} {big.size} {round(os.path.getsize(OUT_WEBP)/1024)} KB")

# --- silhouette profile ----------------------------------------------------
AN = 512
sm = pad.resize((AN, AN), Image.Resampling.LANCZOS)
px = sm.load()
step = AN / COLS
rows = []
for c in range(COLS):
    x0, x1 = int(c * step), max(int((c + 1) * step), int(c * step) + 1)
    top, bot, sum_a, sum_r, sum_b, n = None, None, 0, 0, 0, 0
    for x in range(x0, x1):
        for y in range(AN):
            r, gg, b, al = px[x, y]
            if al < 30:
                continue
            if top is None:
                top = y
            bot = y
            sum_a += al
            sum_r += r * al
            sum_b += b * al
            n += 1
    if top is None or sum_a == 0:
        continue
    cx = (x0 + x1) / 2 / AN * 2 - 1
    rows.append([
        round(cx * 1000),
        round((top / AN * 2 - 1) * 1000),
        round((bot / AN * 2 - 1) * 1000),
        round(min(1, sum_a / (n * 255)) * 1000),
        1 if sum_b / sum_a >= sum_r / sum_a else 0,  # 1 = cyan side, 0 = magenta
    ])

body = ",\n".join("  [%s]" % ",".join(str(v) for v in r) for r in rows)
dart = f"""// GENERATED by brand/intro/gen_mobile_assets.py — do not edit by hand.
// Column profile sampled from assets/brand/mark.webp: [x, top, bottom, energy, chroma]
// All values are scaled by 1000 and expressed in unit space (-1..1 from the mark centre).
const List<List<int>> kSplashColumns = [
{body},
];
"""
os.makedirs(os.path.dirname(OUT_DART), exist_ok=True)
open(OUT_DART, "w").write(dart)
print(f"{OUT_DART} {len(rows)} columns, {round(os.path.getsize(OUT_DART)/1024)} KB")
